### ISSUE TITLE
Create releases on github to use in neovim with Mason plugin manager

### ISSUE THREAD

**Issue by pm4rcin** [kirides/DaedalusLanguageServer#9]
Hi, it'd be great if you could create tagged release with binaries so it could be integrated into Mason registry for quick and easy install in neovim. I'll try to add it to Mason when you provide releases. It could be version tags or a tag the day it was created like rust uses. But I need some info if you could look [here](https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#package-specification). Most things are obvious but for example I'm not sure if it is only for one category or more and also not sure if something should be put to `share` or `opt`.

**Comment by kirides** [comment]
I implemented a release action.

the initial v1.0.0 release is now published.

**Comment by pm4rcin** [comment]
Nice work. But I have a problem that syntax highlight doesn't look like in your screenshots from vscode. I have disabled tree-sitter since it conflicts but some things are still not highlighted. Any tip? 
![20240422_21h23m01s_grim](https://github.com/kirides/DaedalusLanguageServer/assets/37148802/bc8ed5f1-bab4-4706-8ac1-555b5d45177d)
![20240422_21h24m21s_grim](https://github.com/kirides/DaedalusLanguageServer/assets/37148802/17c0f3e1-ed88-46c3-977c-65b4a3972e03)

**Comment by kirides** [comment]
colors highly depend on the theme itself.
the language server just returns semantic data, it's up to a LSP Client to match that with colors for a theme.

maybe this helps: 
https://github.com/neovim/neovim/pull/21100
```
:h lsp-semantic_tokens
```

**Comment by pm4rcin** [comment]
I've tried vanilla theme but it doesn't change anything. One thing I noticed is UPPER CASE VOID is not highlighted while lower is. As for the help I'm not sure what it should show so...

**Comment by pm4rcin** [comment]
@kirides I'm wondering why did you include this line in README. Were there some problems in the past or nvim didn't support something? And what's the intended effect of it because I don't know how it should change highlighting in Daedalus files? https://github.com/kirides/DaedalusLanguageServer/blob/f67a464ffd56fc37c932f456edddf5947b8efe1b/README.md?plain=1#L57

**Comment by kirides** [comment]
i added that part as i like my neovim to actually highlight the active parameter when typing a function
without this, iirc. the "current" parameter is highlighted no different than any others.

**Comment by pm4rcin** [comment]
FYI I've created PRs to add it to mason https://github.com/mason-org/mason-registry/pull/6776 and nvim-lspconfig https://github.com/neovim/nvim-lspconfig/pull/3259. When both will land it would be worth mentioning in README.
